---
- name: Installing andrewrothstein.unarchivedeps
  ansible.builtin.include_role:
    name: andrewrothstein.unarchivedeps
- name: Resolve platform specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: Check for install in {{ traefik_mesh_exe }}
  become: true
  ansible.builtin.stat:
    path: '{{ traefik_mesh_exe }}'
  changed_when: false
  register: traefik_mesh_binary
- name: Downloading and installing traefik-mesh
  when: not traefik_mesh_binary.stat.exists
  block:
    - name: Downloading {{ traefik_mesh_url }}
      become: true
      become_user: root
      ansible.builtin.get_url:
        url: '{{ traefik_mesh_url }}'
        dest: '{{ traefik_mesh_tmp_archive }}'
        mode: '644'
        checksum: '{{ traefik_mesh_checksum }}'
    - name: Mkdir {{ traefik_mesh_install_dir }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ traefik_mesh_install_dir }}'
        mode: '755'
        state: directory
    - name: Unarchiving {{ traefik_mesh_tmp_archive }}
      become: true
      become_user: root
      ansible.builtin.unarchive:
        remote_src: true
        src: '{{ traefik_mesh_tmp_archive }}'
        dest: '{{ traefik_mesh_install_dir }}'
        creates: '{{ traefik_mesh_exe }}'
  always:
    - name: Rm {{ traefik_mesh_tmp_archive }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ traefik_mesh_tmp_archive }}'
        state: absent
- name: Link {{ traefik_mesh_link }} to {{ traefik_mesh_exe }}
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ traefik_mesh_exe }}'
    dest: '{{ traefik_mesh_link }}'
    state: link
